baseurl = "https://box2go.netlify.app/"
DefaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
title = "Box2Go"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
#theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"


[Services]
[Services.Disqus]
# Shortname = "XXX"
[Services.googleAnalytics]
# id = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
subtitle = "Tú compras, nosotros te lo guardamos"
mainSections = ["post", "posts"]
logo = "images/logo.jpg"                          # Expecting square dimensions
favicon = "images/favicon.ico"
dateFormat = "2 de January de 2006"
commit = false
rss = false
comments = false
readingTime = false
wordCount = false
useHLJS = false
socialShare = false
delayDisqus = false
showRelatedPosts = false
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"


[Params.author]
# Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
name = "Box2Go S.A."

website = "https://box2go.netlify.app/"
# email = "youremail@domain.com"
# facebook = "username"
# github = "username"
# gitlab = "username"
# bitbucket = "username"
# twitter = "username"
# reddit = "username"
# linkedin = "username"
# xing = "username"
# stackoverflow = "users/XXXXXXX/username"
# snapchat = "username"
# instagram = "username"
# youtube = "user/username" # or channel/channelname
# soundcloud = "username"
# spotify = "username"
# bandcamp = "username"
# itchio = "username"
# vk = "username"
# paypal = "username"
# telegram = "username"
# 500px = "username"
# codepen = "username"
# mastodon = "url"
# kaggle = "username"
# weibo = "username"
# slack = "username"
# medium = "username"
# discord = "invite code (https://discord.gg/XXXXXXX)"
# strava = "userid"

[[menu.main]]
name = "Inicio"
url = ""
weight = 1

# [[menu.main]]
# name = "About"
# url = "page/about/"
# weight = 3

# [[menu.main]]
# identifier = "samples"
# name = "Productos"
# weight = 2

[[menu.main]]
identifier = "z"
name = "Cajón estándar"
url = "products/cajon-estandar"
weight = 2

[[menu.main]]
name = "Cajón plus"
url = "products/cajon-plus"
weight = 3

[[menu.main]]
name = "Cajón para empresas"
url = "products/cajon-empresas"
weight = 4
